version: '3.7'
services:
  backend:
    build: ./api
    networks:
      - my-network
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    build: ./postgres
    networks:
      - my-network
  httpd:
    build: ./http
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
      - database
networks:
  my-network: