spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://postgres:5432/db_tp1"
    username: guest
    password: guest_pwd
    driver-class-name: org.postgresql.Driver
